local define_mission = {
	["1"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Score",
		["target"] = "EnemyAll",
		["targetValue"] = 100000,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescScore",

	},
	["2"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Score",
		["target"] = "EnemyAll",
		["targetValue"] = 300000,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescScore",

	},
	["3"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Score",
		["target"] = "EnemyAll",
		["targetValue"] = 500000,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescScore",

	},
	["4"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Score",
		["target"] = "EnemyAll",
		["targetValue"] = 700000,
		["rewardType"] = "Cash",
		["rewardValue1"] = 2,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescScore",

	},
	["5"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Score",
		["target"] = "EnemyAll",
		["targetValue"] = 1000000,
		["rewardType"] = "Cash",
		["rewardValue1"] = 3,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescScore",

	},
	["6"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Staff",
		["targetValue"] = 5,
		["rewardType"] = "Money",
		["rewardValue1"] = 1500,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillStaff",

	},
	["7"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Staff",
		["targetValue"] = 50,
		["rewardType"] = "Money",
		["rewardValue1"] = 4000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillStaff",

	},
	["8"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Staff",
		["targetValue"] = 100,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillStaff",

	},
	["9"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Sword",
		["targetValue"] = 5,
		["rewardType"] = "Money",
		["rewardValue1"] = 1500,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillSword",

	},
	["10"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Sword",
		["targetValue"] = 50,
		["rewardType"] = "Money",
		["rewardValue1"] = 4000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillSword",

	},
	["11"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Sword",
		["targetValue"] = 100,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillSword",

	},
	["12"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Club",
		["targetValue"] = 5,
		["rewardType"] = "Money",
		["rewardValue1"] = 1500,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillClub",

	},
	["13"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Club",
		["targetValue"] = 50,
		["rewardType"] = "Money",
		["rewardValue1"] = 4000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillClub",

	},
	["14"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Club",
		["targetValue"] = 100,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillClub",

	},
	["15"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Staff",
		["targetValue"] = 1,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipStaff",

	},
	["16"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Staff",
		["targetValue"] = 3,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipStaff",

	},
	["17"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Staff",
		["targetValue"] = 10,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipStaff",

	},
	["18"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Sword",
		["targetValue"] = 1,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipSword",

	},
	["19"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Sword",
		["targetValue"] = 3,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipSword",

	},
	["20"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Sword",
		["targetValue"] = 10,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipSword",

	},
	["21"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Club",
		["targetValue"] = 1,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipClub",

	},
	["22"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Club",
		["targetValue"] = 3,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipClub",

	},
	["23"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Club",
		["targetValue"] = 10,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipClub",

	},
	["24"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Staff",
		["targetValue"] = 5,
		["rewardType"] = "Money",
		["rewardValue1"] = 1500,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillStaff",

	},
	["25"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Staff",
		["targetValue"] = 50,
		["rewardType"] = "Money",
		["rewardValue1"] = 4000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillStaff",

	},
	["26"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Staff",
		["targetValue"] = 100,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillStaff",

	},
	["27"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Sword",
		["targetValue"] = 5,
		["rewardType"] = "Money",
		["rewardValue1"] = 1500,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillSword",

	},
	["28"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Sword",
		["targetValue"] = 50,
		["rewardType"] = "Money",
		["rewardValue1"] = 4000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillSword",

	},
	["29"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Sword",
		["targetValue"] = 100,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillSword",

	},
	["30"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Club",
		["targetValue"] = 5,
		["rewardType"] = "Money",
		["rewardValue1"] = 1500,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillClub",

	},
	["31"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Club",
		["targetValue"] = 50,
		["rewardType"] = "Money",
		["rewardValue1"] = 4000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillClub",

	},
	["32"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "Club",
		["targetValue"] = 100,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_KillClub",

	},
	["33"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Staff",
		["targetValue"] = 1,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipStaff",

	},
	["34"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Staff",
		["targetValue"] = 3,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipStaff",

	},
	["35"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Staff",
		["targetValue"] = 10,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipStaff",

	},
	["36"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Sword",
		["targetValue"] = 1,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipSword",

	},
	["37"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Sword",
		["targetValue"] = 3,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipSword",

	},
	["38"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Sword",
		["targetValue"] = 10,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipSword",

	},
	["39"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Club",
		["targetValue"] = 1,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipClub",

	},
	["40"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Club",
		["targetValue"] = 3,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipClub",

	},
	["41"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "Club",
		["targetValue"] = 10,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_EquipClub",

	},
	["42"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "WeaponAll",
		["targetValue"] = 10,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Kill",

	},
	["43"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "WeaponAll",
		["targetValue"] = 100,
		["rewardType"] = "Money",
		["rewardValue1"] = 4000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Kill",

	},
	["44"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Kill",
		["target"] = "WeaponAll",
		["targetValue"] = 200,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Kill",

	},
	["45"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "WeaponAll",
		["targetValue"] = 5,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Equip",

	},
	["46"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "WeaponAll",
		["targetValue"] = 10,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Equip",

	},
	["47"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Weapon_Equip",
		["target"] = "WeaponAll",
		["targetValue"] = 20,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Equip",

	},
	["48"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "WeaponAll",
		["targetValue"] = 10,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Kill",

	},
	["49"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "WeaponAll",
		["targetValue"] = 100,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Kill",

	},
	["50"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Kill",
		["target"] = "WeaponAll",
		["targetValue"] = 200,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Kill",

	},
	["51"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "WeaponAll",
		["targetValue"] = 5,
		["rewardType"] = "Money",
		["rewardValue1"] = 1000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Equip",

	},
	["52"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "WeaponAll",
		["targetValue"] = 10,
		["rewardType"] = "Money",
		["rewardValue1"] = 2000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Equip",

	},
	["53"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Weapon_Equip",
		["target"] = "WeaponAll",
		["targetValue"] = 20,
		["rewardType"] = "Money",
		["rewardValue1"] = 4000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescWeapon_Equip",

	},
	["54"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Enemy",
		["target"] = "EnemyAll",
		["targetValue"] = 100,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescEnemy",

	},
	["55"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Enemy",
		["target"] = "EnemyAll",
		["targetValue"] = 500,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescEnemy",

	},
	["56"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Enemy",
		["target"] = "EnemyAll",
		["targetValue"] = 1000,
		["rewardType"] = "Cash",
		["rewardValue1"] = 3,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescEnemy",

	},
	["57"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Enemy",
		["target"] = "EnemyAll",
		["targetValue"] = 100,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescEnemy",

	},
	["58"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Enemy",
		["target"] = "EnemyAll",
		["targetValue"] = 500,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescEnemy",

	},
	["59"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Enemy",
		["target"] = "EnemyAll",
		["targetValue"] = 1000,
		["rewardType"] = "Cash",
		["rewardValue1"] = 3,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescEnemy",

	},
	["60"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Try",
		["target"] = "Stamina",
		["targetValue"] = 3,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescTry",

	},
	["61"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Try",
		["target"] = "Stamina",
		["targetValue"] = 5,
		["rewardType"] = "Money",
		["rewardValue1"] = 5000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescTry",

	},
	["62"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Survivor",
		["missionType2"] = "Try",
		["target"] = "Stamina",
		["targetValue"] = 10,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescTry",

	},
	["63"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Try",
		["target"] = "Stamina",
		["targetValue"] = 3,
		["rewardType"] = "Money",
		["rewardValue1"] = 3000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescTry",

	},
	["64"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Try",
		["target"] = "Stamina",
		["targetValue"] = 5,
		["rewardType"] = "Money",
		["rewardValue1"] = 5000,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescTry",

	},
	["65"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Stage",
		["missionType2"] = "Try",
		["target"] = "Stamina",
		["targetValue"] = 10,
		["rewardType"] = "Cash",
		["rewardValue1"] = 1,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescTry",

	},
	["66"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Shop",
		["missionType2"] = "Buy",
		["target"] = "Artifact",
		["targetValue"] = 1,
		["rewardType"] = "Stamina",
		["rewardValue1"] = 3,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescBuyArtifact",

	},
	["67"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Shop",
		["missionType2"] = "Buy",
		["target"] = "Artifact",
		["targetValue"] = 3,
		["rewardType"] = "Stamina",
		["rewardValue1"] = 5,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescBuyArtifact",

	},
	["68"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Shop",
		["missionType2"] = "Enchant",
		["target"] = "Artifact",
		["targetValue"] = 1,
		["rewardType"] = "Stamina",
		["rewardValue1"] = 3,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescEnchantArtifact",

	},
	["69"] = {
		["takeType"] = "Repetition",
		["missionType1"] = "Shop",
		["missionType2"] = "Enchant",
		["target"] = "Mystique",
		["targetValue"] = 1,
		["rewardType"] = "Stamina",
		["rewardValue1"] = 3,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescEnchantMystique",

	},
	["70"] = {
		["takeType"] = "Fixed",
		["missionType1"] = "Stage",
		["missionType2"] = "Clear",
		["target"] = 0,
		["targetValue"] = 35,
		["rewardType"] = "Cash",
		["rewardValue1"] = 5,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescStage100",

	},
	["71"] = {
		["takeType"] = "Fixed",
		["missionType1"] = "Shop",
		["missionType2"] = "EnchantFull",
		["target"] = "Artifact",
		["targetValue"] = 1,
		["rewardType"] = "Cash",
		["rewardValue1"] = 5,
		["rewardValue2"] = 0,
		["desc"] = 0,
		["desc_localkey"] = "~MissionDescEnchantFullArtifact",

	},

}
return define_mission
