local define_price = {
	["Mantis"] = {
		["index"] = 1,
		["limitType"] = "None",
		["limitValue"] = 0,
		["buyType"] = "None",
		["buyValue"] = 300000,
		["limitBuyType"] = "None",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Drunken"] = {
		["index"] = 2,
		["limitType"] = "Level",
		["limitValue"] = 10,
		["buyType"] = "Money",
		["buyValue"] = 99000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 99,
		["saleFactor"] = 0,

	},
	["Crane"] = {
		["index"] = 3,
		["limitType"] = "Level",
		["limitValue"] = 15,
		["buyType"] = "Money",
		["buyValue"] = 150000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 150,
		["saleFactor"] = 0,

	},
	["Eagle"] = {
		["index"] = 4,
		["limitType"] = "Level",
		["limitValue"] = 20,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Tiger"] = {
		["index"] = 5,
		["limitType"] = "Level",
		["limitValue"] = 30,
		["buyType"] = "Money",
		["buyValue"] = 500000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 500,
		["saleFactor"] = 0,

	},
	["Capoeira"] = {
		["index"] = 6,
		["limitType"] = "None",
		["limitValue"] = 0,
		["buyType"] = "Cash",
		["buyValue"] = 600,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 600,
		["saleFactor"] = 20,

	},
	["MystiqueSlot"] = {
		["index"] = 1,
		["limitType"] = "None",
		["limitValue"] = 0,
		["buyType"] = "None",
		["buyValue"] = 5000,
		["limitBuyType"] = "None",
		["limitBuyValue"] = 5,
		["saleFactor"] = 0,

	},
	["MystiqueSlot"] = {
		["index"] = 2,
		["limitType"] = "Level",
		["limitValue"] = 5,
		["buyType"] = "Money",
		["buyValue"] = 10000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 10,
		["saleFactor"] = 0,

	},
	["MystiqueSlot"] = {
		["index"] = 3,
		["limitType"] = "Level",
		["limitValue"] = 10,
		["buyType"] = "Money",
		["buyValue"] = 20000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 20,
		["saleFactor"] = 0,

	},
	["ArtifactSlot"] = {
		["index"] = 1,
		["limitType"] = "Level",
		["limitValue"] = 5,
		["buyType"] = "None",
		["buyValue"] = 10000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 10,
		["saleFactor"] = 0,

	},
	["ArtifactSlot"] = {
		["index"] = 2,
		["limitType"] = "Level",
		["limitValue"] = 15,
		["buyType"] = "Money",
		["buyValue"] = 30000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 30,
		["saleFactor"] = 0,

	},
	["ArtifactSlot"] = {
		["index"] = 3,
		["limitType"] = "Level",
		["limitValue"] = 20,
		["buyType"] = "Money",
		["buyValue"] = 50000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 50,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 100,
		["limitType"] = "Level",
		["limitValue"] = 1,
		["buyType"] = "Money",
		["buyValue"] = 50000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 100,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 101,
		["limitType"] = "Level",
		["limitValue"] = 15,
		["buyType"] = "Money",
		["buyValue"] = 100000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 200,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 102,
		["limitType"] = "Level",
		["limitValue"] = 10,
		["buyType"] = "Money",
		["buyValue"] = 50000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 100,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 103,
		["limitType"] = "Level",
		["limitValue"] = 20,
		["buyType"] = "Money",
		["buyValue"] = 10000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 50,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 104,
		["limitType"] = "Level",
		["limitValue"] = 25,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 105,
		["limitType"] = "Level",
		["limitValue"] = 30,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 106,
		["limitType"] = "Level",
		["limitValue"] = 28,
		["buyType"] = "Money",
		["buyValue"] = 100000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 200,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 107,
		["limitType"] = "Level",
		["limitValue"] = 20,
		["buyType"] = "Money",
		["buyValue"] = 100000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 200,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 108,
		["limitType"] = "Level",
		["limitValue"] = 18,
		["buyType"] = "Money",
		["buyValue"] = 50000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 100,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 109,
		["limitType"] = "Level",
		["limitValue"] = 13,
		["buyType"] = "Money",
		["buyValue"] = 50000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 100,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 110,
		["limitType"] = "Level",
		["limitValue"] = 7,
		["buyType"] = "Money",
		["buyValue"] = 10000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 50,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 111,
		["limitType"] = "Level",
		["limitValue"] = 11,
		["buyType"] = "Money",
		["buyValue"] = 50000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 100,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 112,
		["limitType"] = "Level",
		["limitValue"] = 23,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 113,
		["limitType"] = "Level",
		["limitValue"] = 5,
		["buyType"] = "Money",
		["buyValue"] = 10000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 50,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 114,
		["limitType"] = "Level",
		["limitValue"] = 17,
		["buyType"] = "Money",
		["buyValue"] = 50000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 100,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 115,
		["limitType"] = "Level",
		["limitValue"] = 12,
		["buyType"] = "Money",
		["buyValue"] = 50000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 100,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 116,
		["limitType"] = "Level",
		["limitValue"] = 35,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 117,
		["limitType"] = "Level",
		["limitValue"] = 32,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 118,
		["limitType"] = "Level",
		["limitValue"] = 29,
		["buyType"] = "Money",
		["buyValue"] = 100000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 200,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 119,
		["limitType"] = "Level",
		["limitValue"] = 40,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 120,
		["limitType"] = "Level",
		["limitValue"] = 50,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 121,
		["limitType"] = "Level",
		["limitValue"] = 53,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 122,
		["limitType"] = "Level",
		["limitValue"] = 55,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 123,
		["limitType"] = "Level",
		["limitValue"] = 58,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},
	["Mystique"] = {
		["index"] = 124,
		["limitType"] = "Level",
		["limitValue"] = 60,
		["buyType"] = "Money",
		["buyValue"] = 300000,
		["limitBuyType"] = "Cash",
		["limitBuyValue"] = 300,
		["saleFactor"] = 0,

	},

}
return define_price
